### ISSUE TITLE
CPace API and functions

### ISSUE THREAD

**Issue by bytemare** [cfrg/draft-irtf-cfrg-cpace#10]
Currently, the draft describes the protocols with words in the CPace section and defines some functions at the end of the spec.
I suggest folding them together, and defining the outer CPace API and main functions in the same section as the protocol description, as well as the smaller inner functions.

**Comment by BjoernMHaase** [comment]
I believe that with a specified concrete API, we would have to integrate too many application-level details into this specification. In fact, I think that with the object-oriented specification of the individual function and parameters, we might have given quite detailed implementation guidance.
