### ISSUE TITLE
Key confirmation

### ISSUE THREAD

**Issue by bytemare** [cfrg/draft-irtf-cfrg-cpace#11]
The Key Confirmation section mentions a MAC function and a new message. With regard to #9 and #10, it could be interesting to add the message structure extension and MAC function in that section.

**Comment by BjoernMHaase** [comment]
We have moved this topic to the security consideration section. There we have added a concrete example on how key confirmation could be safely implemented. However, we did not add test vectors as we believe that explicit key confirmation might be implemented by protocols that anyway have an existing implementation, such as TLS.
