### ISSUE TITLE
Scenarios

### ISSUE THREAD

**Issue by bytemare** [cfrg/draft-irtf-cfrg-cpace#8]
The document mentions different scenarios. A dedicated section enumerating and explaining them would be greatly beneficial to the reader not familiar with them.

**Comment by BjoernMHaase** [comment]
Yes I agree.

I think it might be useful to get a clearer picture on the "personas" that might be reading the draft and tailor it for them. Effectively I see the following sketch of "personas" that might be relevant:

"Archibald" : Is a software architecture engineer for networking applications. Archibald is looking for suitable protocols for his larger solution and mainly interrested in the required input and outputs of the protocol.

"Cody": Is an SW engineer coding low-level crypto code and would like to verify that his implementation matches the specification.

"Veronica": Is a SW engineer that verifies and checks Cody's work and implements network penetration tests and unit tests.

"Thekla": Is a theory-inclined security researcher considering provable security.


I agree that "Archibald" might deserve some more attention. "Thekla" should be given the reference already in the introduction that the document is not written for her but that she should rather have a look at the CPace paper in the first place.

**Comment by BjoernMHaase** [comment]
I think that we addressed that issue in the last major rewrite.
