### ISSUE TITLE
Message structures

### ISSUE THREAD

**Issue by bytemare** [cfrg/draft-irtf-cfrg-cpace#9]
The document mentions messages exchanged between the parties. It would be interesting to have their wire format properly described (e.g. like in rfc8446)

**Comment by BjoernMHaase** [comment]
Actually I believe that specifying the wire format beyond the details that are given here should and needs to be left over to the actual application.

The mandatory part should be, in my opinion to include MSGa and MSGb somehow in a possibly existing ecosystem. For instance how TLS incorporates MSGa and MSGb on the wire will reasonably be different from another protocol such as IPSEC.

However, it might be worth drawing more attention to the fact that actually scalar_mult_verify returns an octet string that is expected in exactly this form on the wire included inside MSGa and MSGb.

**Comment by bytemare** [comment]
> For instance how TLS incorporates MSGa and MSGb on the wire will reasonably be different from another protocol such as IPSEC.

That's interesting. Can you elaborate?

**Comment by BjoernMHaase** [comment]
For instance MSGa would be integrated at some spot in the body of a client hello together with several other fields such as the tls nonce and handshake information.The message on the wire will, thus be fairy different as for a ipsec message.The only important aspect is to find MSGa and MSGb somewhere in the frames of the higher level protocol. I see thus no reason to constrain applications in the way they encode the two cpace messages in their protocol flow.--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 23.01.22, 01:51 schrieb Daniel Bourdrez ***@***.***>:

   
   
   For instance how TLS incorporates MSGa and MSGb on the wire will reasonably be different from another protocol such as IPSEC. 
   
  That's interesting. Can you elaborate?
